kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          image: mbigras/app:2023-07-15
          env:
            - name: ENV
              value: env1
            - name: COLOR
              value: expensiveblue
            - name: PASSWORD
              value: mylastname # Todo: Implement better secrets management.
